learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('learning_logs.urls', namespace='learning_logs')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path, include
from . import views 

app_name = 'learning_logs'
urlpatterns = [
    # Home Page
    path('', views.index, name='index'),

    # Topic page
    path('topics/', views.topics, name='topics'),

    # Individual Topic Page
    path('topics/<int:topic_id>', views.topic, name='topic'),

    # New Topic page
    path('new_topic/', views.new_topic, name='new_topic'),

    # New Entry for topic (new or old)
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),

    # Edit an old entry
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Defines URL patterns for the USERS app"""

from django.urls import path, include
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'

urlpatterns = [
    # Login Page
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),

    # Logout Page
    path('logout/', views.logout_view, name='logout'),

    # Registration Page
    path('register/', views.register, name='register')
]

learning_logs/models.py
import django.db
from django.db import models

# Importing required modules for connecting data to users
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    # Attributes
    """A Topic user is learning about"""
    text = models.CharField(max_length=250)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    # Functions
    def __str__(self):
        """Return a string representation of the model"""
        return self.text
    
class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        """Return a string representation of model"""
        if len(self.text) > 50:
            return self.text[:50] + "..."

        return self.text

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

# Form for new topic
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.TextInput(attrs={'maxlength': 200,'style': 'height: 50px; width: 60%; font-family: cursive; border-radius: 10px; align-items: center; padding: 10px' })}

# Form for new entry
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs= {'placeholder': 'Enter the Entry here', 'cols': 80, 'style': 'border-radius: 10px; font-family: cursive; align-items: center; padding: 10px; width: 100%; height: fit-content'})}

learning_logs/views.py
from django.shortcuts import render

from .models import Topic

# Create your views here.

# view for the home page
def index(request):
    """The home page for Learning Log"""
    return render(request, 'learning_logs/index.html')

# View for the Topics page

# Importing @login_required to restrict access to topics to only logged-in users
from django.contrib.auth.decorators import login_required

@login_required(login_url='users:login')
def topics(request):
    """Show the list of topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}

    return render(request, 'learning_logs/topics.html', context)

# View for the individual topic page

# Importing required modules to check requested entries before retriving them
# importing below modules for error handling
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404

@login_required(login_url='users:login')
def topic(request, topic_id):
    """Show the list of entries for each topic"""
    topic = get_object_or_404(Topic, id=topic_id)

    # Make sure the topic belongs to the current user
    if topic.owner != request.user:
        raise Http404
    
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries':entries}

    return render(request, 'learning_logs/topic.html', context)

# View for the new topic

# Importing required modules
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import TopicForm

@login_required(login_url='users:login')
def new_topic(request):

    """Add a new topic"""
    if request.method != 'POST':
        # No data submitted, create a blank form
        form = TopicForm()
    else:
        # POST data submitted, process data
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

# View for creating new entry

# Importing required modules
from .forms import EntryForm

@login_required(login_url='users:login')
def new_entry(request, topic_id):
    """ Add a new entry for a particular topic"""
    topic = Topic.objects.get(id= topic_id)

    # Make sure the topic belongs to the current user
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # No data submitted, create a blank form
        form = EntryForm()
    else:
        # POST data submitted, process data
        form = EntryForm(data= request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    
    context = {'topic': topic, 'form':form}
    return render(request, 'learning_logs/new_entry.html', context)

# View for editing entries

# Importing required modules
from .models import Topic, Entry

@login_required(login_url='users:login')
def edit_entry(request, entry_id):
    """Edit an existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    # Make sure if the current user is the owner of the topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry
        form = EntryForm(instance=entry)
    else:
        # POST data submitted, process data
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/learning_logs/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body style="background-color: #222327;">

    <nav class="navbar navbar-expand-lg bg-body-inherit" style="font-family: cursive; border-bottom: 1px solid antiquewhite; width: 100%;">

      <div class="container-fluid">

        <a style="color: antiquewhite;padding: 5px; font-weight: 700;" class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" style="background-color: antiquewhite">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item mx-2">
              <a style="color: antiquewhite;" class="nav-link" aria-current="page" href="{% url 'learning_logs:topics' %}">Topics</a>
            </li>
          </ul>
            
            <ul class="nav navbar-nav ms-auto">
              {% if user.is_authenticated %}
                <li class="nav-item mx-2" style="padding: 5px;">
                  <a style="color: antiquewhite;">
                    <span>
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-raised-hand" viewBox="0 0 16 16">
                        <path d="M6 6.207v9.043a.75.75 0 0 0 1.5 0V10.5a.5.5 0 0 1 1 0v4.75a.75.75 0 0 0 1.5 0v-8.5a.25.25 0 1 1 .5 0v2.5a.75.75 0 0 0 1.5 0V6.5a3 3 0 0 0-3-3H6.236a1 1 0 0 1-.447-.106l-.33-.165A.83.83 0 0 1 5 2.488V.75a.75.75 0 0 0-1.5 0v2.083c0 .715.404 1.37 1.044 1.689L5.5 5c.32.32.5.754.5 1.207"/>
                        <path d="M8 3a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3"/>
                      </svg>
                  </span> Hello, {{ user.username }}!</a>
                </li>
                <li class="nav-item mx-2">
                  <button class="btn btn-danger">
                    <a style="color: antiquewhite; text-decoration: none;" href="{% url 'users:logout' %}">Log out</a>
                  </button>
                </li>
              {% else %}
                <li class="nav-item mx-2">
                  <button class="btn btn-secondary">
                    <a style="color: antiquewhite; text-decoration: none;" href="{% url 'users:register' %}">Register</a>
                  </button>
                </li>
                <li class="nav-item mx-2">
                  <button class="btn btn-primary">
                    <a style="color: antiquewhite; text-decoration: none;" href="{% url 'users:login' %}">Login</a>
                  </button>
                </li>
              {% endif %}
            </ul>
        </div>

      </div>
    </nav>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

{% block header %}{% endblock %}

{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <div class="container-fluid" style="text-align: center;">
        <p style=" font-size:xxx-large; margin-bottom: 10px; font-family: cursive; font-weight: 800; font-style: italic; color: antiquewhite;">
            <a style="text-decoration: none; color: antiquewhite;" href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </p>
    
    
        <div class="container-fluid" style="text-align: center; width: 90%;">
            <p>
                <h4 style="font-family: cursive; color: antiquewhite;">Edit Entry:</h4>
            </p>

            <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-warning" style="font-family: cursive;" name="submit">Save Changes</button>
            </form>
        </div>
    </div>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}

<div class="container" style=" text-align: center; color: antiquewhite; background-color: inherit; margin: auto;">
  <div class="row" style="margin: auto; margin-top: 50px;">
    <div class="col-md-6 d-flex align-items-center" style="text-align: center; align-items: center;">

      <svg class="img-fluid mx-auto d-block" xmlns="http://www.w3.org/2000/svg" width="300px" height="300px" fill="currentColor" class="bi bi-card-checklist mx-auto d-block" viewBox="0 0 16 16">
          <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2z"/>
          <path d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0M7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0"/>
      </svg>

    </div>
    <div class="col-md-6 d-flex align-items-center">

      <div style="text-align:left; margin: 10px; width: 600px; font-family: cursive;">
        <p style="font-family: cursive;">
          <h3 style="font-weight: bold;">Unleash Your Learning Potential with Our Learning Log!</h3>
    
          <p>Tired of scattered notes and forgotten ideas? Our Learning Log is here to revolutionize the way you learn and organize your thoughts. It's your personal digital notebook, tailored to your unique learning style.</p>
    
          <ul>
            <div style="margin-bottom: 10px;">
              <span style="margin-right: 5px; margin-left: none;">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="yellow" class="bi bi-info-circle-fill" viewBox="0 0 16 16">
                  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16m.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2"/>
                </svg>
              </span>
              <span style="font-weight:bolder; font-size: x-large;">Why Choose Our Learning Log?</span>
            </div>
    
            <li><span style="text-decoration: underline; font-weight:400; font-style: italic;">Centralized Knowledge Base:</span> Keep all your notes, ideas, and reflections in one place.</li>
            <li><span style="text-decoration: underline; font-weight:400; font-style: italic;">Organization:</span> Categorize and tag your notes for quick and efficient retrieval.</li>
            <li><span style="text-decoration: underline; font-weight:400; font-style: italic;">Enhanced Learning Experience:</span> Reflect on your progress, set goals, and track your learning journey.</li>
            <li><span style="text-decoration: underline; font-weight:400; font-style: italic;">Secure and Private:</span> Your notes are safe and accessible only to you.</li>
            <li><span style="text-decoration: underline; font-weight:400; font-style: italic;">User-Friendly Interface:</span> A simple and intuitive design that makes note-taking a breeze.</li>
          </ul>
    
          Start Your Learning Journey Today!
    
          Create an account and unlock the full potential of our Learning Log. It's time to take control of your learning and achieve your goals. 
    
        </p>
      </div>

    </div>
  </div>
</div>

<table class="table-dark" style=" background-color: inherit; width: 80%; margin: 20px auto; display: flex; flex-direction: column;">
  <tbody>
    <tr style="background-color: inherit;">
      <td style="width: 50%; text-align: center;">
        
      </td>
      <td style="width: 50%; text-align: center;">
        
      </td>
    </tr>
  </tbody>
</table>

  



{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <div style="margin: 10px; margin-bottom: 5px;">
        <p>
            <a href="{% url 'learning_logs:topic' topic.id %}" style="text-decoration: none; color: antiquewhite;">
                <h3 style="font-family: cursive;">{{ topic }}</h3>
            </a>
        </p>
    </div>

    <div style="margin: 10px; margin-top: 5px;">
        <p>
            <h3 style="text-align:left; margin-bottom: 15px; font-family: cursive; font-weight: 500; font-style: italic;">Add a new entry:</h3>
        </p>
        <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-warning btn-lg" type="submit" value="Add Entry" style="font-family: cursive; margin: 5px; padding: 10px;">
        </form>

    </div>
    

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}


{% block header %}
    <div class="container-fluid" style="text-align: center; margin: auto; margin-top: 30px;">
        <h1 style="font-family: cursive; font-weight: bold; font-style: italic; color: antiquewhite; font-size: 2em;">Enter the New topic here:</h1>
    </div>
{% endblock %}

{% block content %}
    <div class="container-fluid" style=" text-align: center; margin: auto; margin-top: 30px;">

        <form action="{% url 'learning_logs:new_topic' %}" method="post" style="width: 100%;">
            {% csrf_token %}
            {{ form.as_p }}

            <input class="btn btn-primary btn-info btn-lg" type="submit" value="Submit" style="margin-top: 15px; font-family: cursive;">
        </form>
    </div>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <div class="container-fluid" style="margin: auto; margin-bottom: 5px;">
        
        <div class="container-fluid" style="text-align: center;">
            <h2 style=" font-size:xx-large; margin-bottom: 10px; font-family: cursive; font-weight: 800; font-style: italic; color: antiquewhite;"> {{ topic }}</h2>

            <a class="btn btn-primary btn-warning" href="{% url 'learning_logs:new_entry' topic.id %}" 
                style="font-size: large; font-family: cursive; margin-top: 20px; width: 300px;">Add a new entry:
            </a>
        </div>

        <ul class="list-group" style="margin-top: 20px; background-color: inherit;">
            {% for entry in entries %}
            <li class="list-group-item" style="font-family: cursive; font-weight: 300; background-color: inherit; color: antiquewhite;">
                <p>{{ entry.date_added|date:"M d, Y H:i" }}</p>
                <p>{{ entry.text }}</p>
                <p>
                    <a class="btn btn-primary" href="{% url 'learning_logs:edit_entry' entry.id %}" style="text-decoration: none; color: antiquewhite; font-family: cursive;">Edit Entry</a>
                </p>
            </li>
            {% empty %}
            <li class="list-group-item">There are no entries for this topic.</li>
            {% endfor %}
        </ul>
    </div>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block header %}
    <div class="container-fluid" style="text-align: center; margin-bottom: auto; margin-top: 50px;">
        <h1 style="font-family: cursive; color: antiquewhite; font-size: 2.5em;">Your Topics:</h1>
    </div>
{% endblock %}

{% block content %}

    <div class="container-fluid" style="margin-top: 50px;">
        <ul class="list-group" style="background-color: inherit;">
            {% for topic in topics %}
            <li class="list-group-item" style="font-size: x-large; font-family:cursive; background-color: inherit;">
                <a href="{% url 'learning_logs:topic' topic.id %}" style="text-decoration: none; color: antiquewhite;">{{ topic }}</a>
            </li>
            {% empty %}
            <li class="list-group-item" style="font-size: x-large; font-family: cursive; background-color: inherit; color: antiquewhite;">No topics have been added yet.</li>
            {% endfor %}
        </ul>
    
        <div class="container-fluid" style="text-align: center;">
            <a class="btn btn-primary btn-warning" href="{% url 'learning_logs:new_topic' %}" 
            style="font-size: large; font-family: cursive; margin-top: 25px; padding: 8px 20px;">Add a new topic:</a>
        </div>
    </div>

{% endblock content %}