learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('learning_logs.urls', namespace='learning_logs')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path, include
from . import views 

app_name = 'learning_logs'
urlpatterns = [
    # Home Page
    path('', views.index, name='index'),

    # Topic page
    path('topics/', views.topics, name='topics'),

    # Individual Topic Page
    path('topics/<int:topic_id>', views.topic, name='topic'),

    # New Topic page
    path('new_topic/', views.new_topic, name='new_topic'),

    # New Entry for topic (new or old)
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),

    # Edit an old entry
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Defines URL patterns for the USERS app"""

from django.urls import path, include
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'

urlpatterns = [
    # Login Page
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),

    # Logout Page
    path('logout/', views.logout_view, name='logout'),

    # Registration Page
    path('register/', views.register, name='register')
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout

# View for Logout
def logout_view(request):
    """Logging out the user"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

# View for registering new users

# Importing required modules
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display Blank registeration form
        form = UserCreationForm()
    else:
        # Process Completed Form
        form = UserCreationForm(data= request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username, password=form.cleaned_data['password1'])
            if authenticated_user is not None:
                login(request, authenticated_user)
                return HttpResponseRedirect(reverse('learning_logs:index'))
    
    context = {'form': form}
    return render(request, 'users/register.html', context)

users/templates/users/login.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <div class="container-fluid" style="text-align: center; margin-bottom: 30px; margin-top: 130px;">
        <h1 style="font-family: cursive; color: antiquewhite; font-size: 2.5em;">Log in to your account</h1>
    </div>
    
{% endblock %}

{% block content %}

    {% if form.errors %}
    <div class="container-fluid" style="text-align: center;">
        <p style="font-family: cursive; color: antiquewhite;">Your Username and Password didn't match. Please try again!</p>
    </div>
    {% endif %}

    <form action="{% url 'users:login' %}" method="post" style="color: antiquewhite; font-family: cursive; text-align: center; margin: auto;">
        {% csrf_token %}
        {{ form.as_p }}

        <button class="btn btn-primary" name="submit" style=" width: 100px; font-family: cursive; font-weight: 600; padding: 10px; color: antiquewhite;">Login</button>

        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %}

    

users/templates/users/register.html
{% extends "learning_logs/base.html" %}

<div class="container-fluid" style="text-align: center;">
    {% block header %}

        <div class="container-fluid" style="text-align: center; margin-bottom: 30px; margin-top: 130px;">
            <h1 style="font-family: cursive; color: antiquewhite; font-size: 2.5em; font-weight: bold;">Sign Up for your account</h1>
        </div>
        
    {% endblock %}

    {% block content %}
        <div class="container-fluid" style="margin:auto; width: fit-content;">
            <form method="post" action="{% url 'users:register' %}" style=" width: fit-content; font-family: cursive; color: antiquewhite; margin-top: 30px;">
                {% csrf_token %}
                {{ form.as_p }}
                
                <div style="text-align: center;">
                    <button class="btn btn-success mx-auto" name="submit" style=" margin: 15px; padding:5px 35px; width: fit-content;">Register</button>
                    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
                </div>
                <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
            </form>
        </div>
    {% endblock content %}
</div>